import type { Metadata } from "next";
import "./globals.css";
import { titillium } from "./fonts";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titillium.className} pt-[140px] min-h-screen flex flex-col`}
      >
        <Header />
        <main className="max-w-7xl mx-auto text-zinc-600">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
